version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      
  redis:
    image: redis
    restart: unless-stopped

  web:
    image: glitchtip/glitchtip
    depends_on:
      - postgres
      - redis
    ports:
      - 80:8000
    environment:
      - DATABASE_URL=${DATABASE_URL} 
      - SECRET_KEY=${SECRET_KEY} 
      - PORT=${PORT} 
      - EMAIL_URL=${EMAIL_URL} 
      - GLITCHTIP_DOMAIN=${GLITCHTIP_DOMAIN} 
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
    restart: unless-stopped

  worker:
    image: glitchtip/glitchtip
    command: ./bin/run-celery-with-beat.sh
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=${DATABASE_URL} 
      - SECRET_KEY=${SECRET_KEY} 
      - PORT=${PORT} 
      - EMAIL_URL=${EMAIL_URL} 
      - GLITCHTIP_DOMAIN=${GLITCHTIP_DOMAIN} 
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
    restart: unless-stopped

  migrate:
    image: glitchtip/glitchtip
    depends_on: 
      - postgres
      - redis
    command: "./manage.py migrate"
    environment:
      - DATABASE_URL=${DATABASE_URL} 
      - SECRET_KEY=${SECRET_KEY} 
      - PORT=${PORT} 
      - EMAIL_URL=${EMAIL_URL} 
      - GLITCHTIP_DOMAIN=${GLITCHTIP_DOMAIN} 
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}